#!/usr/bin/env bash
# Validate the final, repacked AppImage bytes before release signing.
#
# This file is sourceable for fixture tests. When executed directly it extracts
# exactly one AppImage from a foreign working directory, validates the released
# sharun layout, and optionally performs a bounded Xvfb startup smoke.
#
# Usage: validate-appimage-runtime.sh <final.AppImage>
#
# Env:
#   APPIMAGE_RUNTIME_SMOKE — set to 1 to require the bounded Xvfb startup smoke;
#                            otherwise only static final-artifact checks run

set -euo pipefail

RUNTIME_VALIDATOR_SCRIPT_DIR="$(
  cd "$(dirname "${BASH_SOURCE[0]}")" && pwd
)"
# shellcheck source=strip-appimage-graphics-libs.sh
source "$RUNTIME_VALIDATOR_SCRIPT_DIR/strip-appimage-graphics-libs.sh"

# The production NEEDED contract, in ONE place. `validate_extracted_appdir`
# takes it as its default and the direct-invocation branch at the bottom pins it,
# so a caller-supplied `APPIMAGE_EXPECTED_NEEDED` can relax the check for a
# fixture but never for a real release artifact. Both readers name this constant
# — the previous code duplicated the list, and the stale copy (libcef.so)
# outlived CEF by two weeks.
#
# Verified against a real linuxdeploy bundle on both Linux arches: usr/bin/OpenHuman
# declares and bundles libxdo.so.3 and libwebkit2gtk-4.1.so.0.
APPIMAGE_PRODUCTION_NEEDED="libxdo.so.3 libwebkit2gtk-4.1.so.0"

runtime_validation_error() {
  echo "[appimage-runtime] ERROR: $*" >&2
  return 1
}

# Print enough of the AppDir to diagnose a layout change from the log alone.
# The absence of this is why the CEF->Wry bundler swap took four release runs to
# understand: the validator said "not sharun" and showed nothing else.
dump_appdir_tree() {
  local appdir="$1"
  echo "[appimage-runtime] AppDir root:"
  ls -la "$appdir" 2>/dev/null | sed 's/^/[appimage-runtime]   /'
  local d
  for d in usr/bin usr/share/applications apprun-hooks; do
    [ -d "$appdir/$d" ] || continue
    echo "[appimage-runtime] $d:"
    ls -la "$appdir/$d" 2>/dev/null | sed 's/^/[appimage-runtime]   /'
  done
  if [ -d "$appdir/usr/lib" ]; then
    echo "[appimage-runtime] usr/lib: $(find "$appdir/usr/lib" -maxdepth 1 -type f | wc -l | tr -d ' ') files"
  fi
}

# Classify the launcher layout. Prints: sharun | linuxdeploy | unknown.
# Returns 0 for a recognised layout, 1 for unknown.
#
# The two marker sets are disjoint, so classify positively on both rather than
# treating "not sharun" as an error. `unknown` is still fatal: silently skipping
# validation on an unrecognised bundle is exactly how this class of bug ships.
appdir_layout() {
  local appdir="$1"

  # Structural markers first (cheap); the string probe is the historical
  # fallback for a bundle that ships sharun under another name.
  if [ -e "$appdir/sharun" ] \
    || [ -e "$appdir/shared/lib/lib.path" ] \
    || [ -d "$appdir/shared/bin" ] \
    || uses_sharun_launcher "$appdir"; then
    echo sharun
    return 0
  fi

  # AppRun.wrapped is conclusive: only linuxdeploy's apprun-hook wrapper creates
  # it, and tauri always passes `--plugin gtk`, whose hook always triggers the
  # wrapper. The second arm covers a hypothetical hook-less build where AppRun
  # stays the AppImageKit ELF.
  if [ -d "$appdir/usr/bin" ] && [ -d "$appdir/usr/lib" ] \
    && { [ -f "$appdir/AppRun.wrapped" ] || is_executable_elf "$appdir/AppRun"; }; then
    echo linuxdeploy
    return 0
  fi

  echo unknown
  return 1
}

# Echo the absolute path of the main application ELF for a given layout.
appdir_main_binary() {
  local appdir="$1"
  local layout="$2"
  local desktop exec_name
  case "$layout" in
    sharun)
      printf '%s\n' "$appdir/shared/bin/OpenHuman"
      return 0
      ;;
    linuxdeploy)
      # Read the real desktop file, not the AppDir-root symlink: `find -type f`
      # uses lstat and would miss it.
      desktop="$(
        find "$appdir/usr/share/applications" -maxdepth 1 -name '*.desktop' -print -quit 2>/dev/null
      )"
      [ -n "$desktop" ] || return 1
      exec_name="$(sed -n 's/^Exec=//p' "$desktop" | head -n1 | awk '{print $1}' | tr -d '\42\47')"
      [ -n "$exec_name" ] || return 1
      printf '%s\n' "$appdir/usr/bin/$exec_name"
      return 0
      ;;
  esac
  return 1
}

# linuxdeploy-specific structural assertions.
validate_linuxdeploy_appdir() {
  local appdir="$1"

  # AppRun is a bash wrapper generated by linuxdeploy; the AppImageKit ELF was
  # renamed to AppRun.wrapped. Requiring AppRun to be an ELF can never pass.
  local apprun="$appdir/AppRun"
  [ -f "$apprun" ] && [ -x "$apprun" ] \
    || { runtime_validation_error "AppRun is missing or not executable"; return 1; }
  head -c 2 "$apprun" | grep -q '#!' \
    || { runtime_validation_error "AppRun is not a script; expected the linuxdeploy wrapper"; return 1; }
  grep -q 'AppRun\.wrapped' "$apprun" \
    || { runtime_validation_error "AppRun does not hand off to AppRun.wrapped"; return 1; }
  is_executable_elf "$appdir/AppRun.wrapped" \
    || { runtime_validation_error "AppRun.wrapped is not an executable ELF"; return 1; }

  # Every hook the wrapper sources must exist, or startup dies in `set -e`.
  local hook
  if [ -d "$appdir/apprun-hooks" ]; then
    while IFS= read -r -d '' hook; do
      grep -Fq "$(basename "$hook")" "$apprun" \
        || { runtime_validation_error "apprun-hooks/$(basename "$hook") is not sourced by AppRun"; return 1; }
    done < <(find "$appdir/apprun-hooks" -maxdepth 1 -type f -print0)
  fi

  local desktop_count
  desktop_count="$(find "$appdir/usr/share/applications" -maxdepth 1 -name '*.desktop' 2>/dev/null | wc -l | tr -d ' ')"
  [ "$desktop_count" = "1" ] \
    || { runtime_validation_error "expected exactly one desktop file under usr/share/applications, found $desktop_count"; return 1; }

  local desktop
  desktop="$(find "$appdir/usr/share/applications" -maxdepth 1 -name '*.desktop' -print -quit)"
  echo "[appimage-runtime] desktop entry ($desktop):"
  sed 's/^/[appimage-runtime]   /' "$desktop"
  local key
  for key in Exec Icon Name; do
    grep -q "^${key}=" "$desktop" \
      || { runtime_validation_error "desktop entry is missing ${key}="; return 1; }
  done

  # -e follows symlinks: the AppDir-root icon and .DirIcon are relative symlinks
  # into usr/share/icons, NOT regular files.
  [ -e "$appdir/.DirIcon" ] \
    || { runtime_validation_error ".DirIcon does not resolve"; return 1; }

  [ -n "$(find "$appdir/usr/lib" -maxdepth 1 -type f -name '*.so*' -print -quit 2>/dev/null)" ] \
    || { runtime_validation_error "usr/lib contains no shared libraries"; return 1; }

  return 0
}

# sharun-specific structural assertions (the pre-Wry layout), unchanged in
# substance and kept so a sharun bundle still validates.
validate_sharun_appdir() {
  local appdir="$1"
  local lib_path="$appdir/shared/lib/lib.path"
  if [ -f "$lib_path" ]; then
    echo "[appimage-runtime] shared/lib/lib.path:"
    sed 's/^/[appimage-runtime]   /' "$lib_path"
  else
    echo "[appimage-runtime] shared/lib/lib.path: <missing>"
  fi

  local executable
  for executable in \
    "$appdir/AppRun" \
    "$appdir/sharun" \
    "$appdir/bin/OpenHuman" \
    "$appdir/shared/bin/OpenHuman"; do
    if ! is_executable_elf "$executable"; then
      runtime_validation_error "${executable#"$appdir"/} is not an executable ELF"
      return 1
    fi
  done

  local alias
  for alias in "$appdir/AppRun" "$appdir/bin/OpenHuman"; do
    if [ "$alias" -ef "$appdir/sharun" ] || cmp -s "$alias" "$appdir/sharun"; then
      continue
    fi
    runtime_validation_error "${alias#"$appdir"/} does not match sharun"
    return 1
  done

  validate_sharun_lib_path "$appdir" || return 1
  validate_appimage_required_libs "$appdir" || return 1
  return 0
}

validate_extracted_appdir() {
  local appdir="$1"
  local layout
  # `|| true` matters: this script runs under `set -e`, and appdir_layout returns
  # non-zero for an unrecognised layout. Without it the assignment aborts the
  # whole script and the diagnostic below never prints - which is precisely the
  # "it just says no and shows nothing" failure this rewrite exists to remove.
  layout="$(appdir_layout "$appdir" || true)"

  echo "[appimage-runtime] Validating extracted AppDir: $appdir"
  echo "[appimage-runtime] Detected launcher layout: $layout"
  dump_appdir_tree "$appdir"

  case "$layout" in
    sharun)      validate_sharun_appdir "$appdir" || return 1 ;;
    linuxdeploy) validate_linuxdeploy_appdir "$appdir" || return 1 ;;
    *)
      runtime_validation_error \
        "unrecognised AppDir layout: no sharun markers and no linuxdeploy AppRun wrapper"
      return 1
      ;;
  esac

  local main_binary
  main_binary="$(appdir_main_binary "$appdir" "$layout")" || {
    runtime_validation_error "could not resolve the main application binary for the $layout layout"
    return 1
  }
  is_executable_elf "$main_binary" \
    || { runtime_validation_error "${main_binary#"$appdir"/} is not an executable ELF"; return 1; }

  local needed
  if ! needed="$(patchelf --print-needed "$main_binary")"; then
    runtime_validation_error "could not read NEEDED entries from ${main_binary#"$appdir"/}"
    return 1
  fi
  echo "[appimage-runtime] ${main_binary#"$appdir"/} NEEDED entries:"
  if [ -n "$needed" ]; then
    printf '%s\n' "$needed" | sed 's/^/[appimage-runtime]   /'
  else
    echo "[appimage-runtime]   <none>"
  fi

  local lib_roots=("$appdir/usr/lib" "$appdir/shared/lib" "$appdir/lib")

  # Report which NEEDED entries are bundled and which are expected from the
  # host. Deliberately NOT fatal: failing on every unbundled entry would require
  # this script to carry its own copy of the AppImage excludelist (glibc, libGL,
  # libX11, ...), and a stale copy of exactly that kind of list is the failure
  # mode being fixed here. The tripwire below is the assertion; this is evidence.
  local entry root bundled
  for entry in $needed; do
    bundled=""
    for root in "${lib_roots[@]}"; do
      [ -d "$root" ] || continue
      if [ -n "$(find "$root" -name "$entry" -print -quit 2>/dev/null)" ]; then
        bundled="$root"
        break
      fi
    done
    if [ -n "$bundled" ]; then
      echo "[appimage-runtime]   bundled:   $entry"
    else
      echo "[appimage-runtime]   from host: $entry"
    fi
  done

  # Tripwire for libraries that have historically vanished from the bundle
  # silently. libxdo is linked directly by enigo via #[link(name = "xdo")] - not
  # through any crate, so it does not appear in Cargo.lock - and its absence
  # segfaulted the app on launch (#4020). libcef.so used to be on this list; CEF
  # was removed in #5456 and no build can produce it any more.
  #
  # Both halves are fatal, and they catch different regressions. A NEEDED entry
  # that is not bundled is #4020 itself: the loader fails at startup. An entry
  # that is no longer declared at all means the dependency was dropped upstream
  # — no segfault, but a silent capability loss, which is precisely the class of
  # regression this tripwire exists to surface. Warning instead would put it in a
  # 90-minute release log where nobody reads it. If a drop is intentional, remove
  # the name from APPIMAGE_PRODUCTION_NEEDED in the same commit.
  local expected_needed="${APPIMAGE_EXPECTED_NEEDED-$APPIMAGE_PRODUCTION_NEEDED}"
  local needed_name found
  for needed_name in $expected_needed; do
    if ! printf '%s\n' "$needed" | grep -Fxq "$needed_name"; then
      runtime_validation_error \
        "${main_binary#"$appdir"/} is missing NEEDED entry '$needed_name'"
      return 1
    fi
    found=0
    for root in "${lib_roots[@]}"; do
      [ -d "$root" ] || continue
      if [ -n "$(find "$root" -name "$needed_name" -print -quit 2>/dev/null)" ]; then
        found=1
        break
      fi
    done
    if [ "$found" -ne 1 ]; then
      runtime_validation_error \
        "'$needed_name' is NEEDED by ${main_binary#"$appdir"/} but is not bundled in the AppDir"
      return 1
    fi
  done

  # Forbidden build-runner RPATHs. `patchelf --print-rpath` reports DT_RUNPATH as
  # well as DT_RPATH, which matters here: linuxdeploy rewrites paths with
  # `patchelf --set-rpath`, and modern patchelf emits RUNPATH.
  local elf rpath
  for root in \
    "$appdir/shared/bin" \
    "$appdir/shared/lib" \
    "$appdir/bin" \
    "$appdir/lib" \
    "$appdir/usr/bin" \
    "$appdir/usr/lib"; do
    [ -d "$root" ] || continue
    while IFS= read -r -d '' elf; do
      is_elf "$elf" || continue
      rpath="$(patchelf --print-rpath "$elf" 2>/dev/null || true)"
      case "$rpath" in
        *"/home/runner/"*|*"/__w/"*)
          runtime_validation_error \
            "${elf#"$appdir"/} retains forbidden build-runner RPATH '$rpath'"
          return 1
          ;;
      esac
    done < <(find "$root" -type f -print0)
  done
}

smoke_extracted_apprun() {
  local appdir="$1"
  local foreign_cwd="$2"
  local log_file="$3"

  command -v timeout >/dev/null 2>&1 \
    || { runtime_validation_error "timeout is required for the AppImage smoke"; return 1; }
  command -v xvfb-run >/dev/null 2>&1 \
    || { runtime_validation_error "xvfb-run is required for the AppImage smoke"; return 1; }

  echo "[appimage-runtime] Smoking AppRun from AppDir: $appdir"
  echo "[appimage-runtime] Smoke caller CWD: $foreign_cwd"

  local temp_root
  temp_root="$(dirname "$foreign_cwd")"
  local smoke_home="$temp_root/home"
  local smoke_config="$temp_root/config"
  local smoke_data="$temp_root/data"
  local smoke_cache="$temp_root/cache"
  mkdir -p \
    "$foreign_cwd" \
    "$smoke_home" \
    "$smoke_config" \
    "$smoke_data" \
    "$smoke_cache"

  local -a unset_args=()
  local secret_name
  for secret_name in \
    GITHUB_TOKEN \
    GH_TOKEN \
    OPENHUMAN_CEF_NO_SANDBOX \
    TAURI_SIGNING_PRIVATE_KEY \
    TAURI_SIGNING_PRIVATE_KEY_PASSWORD \
    SENTRY_AUTH_TOKEN; do
    unset_args+=(-u "$secret_name")
  done
  while IFS= read -r secret_name; do
    [ -n "$secret_name" ] && unset_args+=(-u "$secret_name")
  done < <(compgen -v OPENAI_ || true)

  # ── D-Bus session bus for the smoke window ─────────────────────────────────
  #
  # A real desktop user always launches the AppImage inside a session that has a
  # D-Bus session bus; a CI runner does not. `tauri-plugin-single-instance` calls
  # `zbus::blocking::connection::Builder::session().unwrap()` in its `setup()`,
  # so with no usable bus it panics before any window exists:
  #
  #   thread 'main' panicked at plugins/single-instance/src/platform_impl/linux.rs:57
  #   called `Result::unwrap()` on an `Err` value:
  #     Address("unsupported transport 'disabled'")
  #
  # ...which is exactly how the Release Production ubuntu smoke failed (exit 101,
  # actions/runs/30393949588). Chromium logs the same underlying condition as
  # "Failed to connect to the bus: Could not parse server address".
  #
  # `app/scripts/e2e-run-session.sh` already solves this for the desktop e2e
  # runner by starting a bus with `dbus-launch`; the AppImage smoke never got the
  # same treatment. Wrapping in `dbus-run-session` is the modern equivalent and
  # needs no explicit teardown — the bus dies with the wrapped command, so the
  # 15s `timeout` still bounds everything.
  #
  # Echo the inherited value first: whether it arrives as `disabled`, `disabled:`
  # or unset changes which code path the app takes, and the failing log gave us
  # no way to tell.
  echo "[appimage-runtime] Inherited DBUS_SESSION_BUS_ADDRESS=${DBUS_SESSION_BUS_ADDRESS:-<unset>}"

  # Always drop the inherited value: the wrapper below supplies a real one, and
  # if no wrapper is available a poisoned `disabled` must not reach the app —
  # with the variable absent the app's own `can_register_single_instance_plugin()`
  # probe falls back to inspecting `$XDG_RUNTIME_DIR/bus`, whereas the literal
  # string `disabled` is precisely what zbus refuses to parse.
  unset_args+=(-u DBUS_SESSION_BUS_ADDRESS)

  local -a dbus_wrapper=()
  if command -v dbus-run-session >/dev/null 2>&1; then
    dbus_wrapper=(dbus-run-session --)
    echo "[appimage-runtime] Providing a session bus via dbus-run-session"
  elif command -v dbus-launch >/dev/null 2>&1; then
    # Older images ship dbus-launch (from dbus-x11) but not dbus-run-session.
    dbus_wrapper=(dbus-launch --exit-with-session)
    echo "[appimage-runtime] Providing a session bus via dbus-launch"
  else
    echo "[appimage-runtime] WARNING: neither dbus-run-session nor dbus-launch found;" \
      "smoking without a session bus (single-instance will be skipped)"
  fi

  local status
  if (
    cd "$foreign_cwd"
    timeout --signal=TERM --kill-after=5s 15s \
      xvfb-run -a --server-args="-screen 0 1280x960x24" \
      env "${unset_args[@]}" \
        HOME="$smoke_home" \
        XDG_CONFIG_HOME="$smoke_config" \
        XDG_DATA_HOME="$smoke_data" \
        XDG_CACHE_HOME="$smoke_cache" \
        OPENHUMAN_CEF_PREWARM=0 \
        OPENHUMAN_DISABLE_GPU=1 \
        ${dbus_wrapper[@]+"${dbus_wrapper[@]}"} \
        "$appdir/AppRun"
  ) >"$log_file" 2>&1; then
    status=0
  else
    status=$?
  fi

  # Loader failures, matched GENERICALLY rather than by library name. The
  # previous version listed `anylinux.so`, `libxdo.so.3` and `libcef.so`
  # individually, which meant the guard only caught a library someone had
  # thought of in advance — and one of those three (libcef.so) had already
  # outlived the runtime that produced it. The dynamic loader's own wording is
  # the stable thing to match, so a library nobody predicted still trips it.
  # `test-strip-appimage-rpaths.sh` pins this breadth by feeding the smoke a
  # `cannot open shared object file` diagnostic and requiring a failure.
  #
  # No false-positive risk against the real bundle: none of these three strings
  # appears anywhere in the fork demo run's output, including its successful
  # 15-second smoke on both architectures.
  local forbidden=0
  if grep -Eiq 'cannot open shared object file' "$log_file"; then
    forbidden=1
  fi
  if grep -Eiq 'error while loading shared libraries' "$log_file"; then
    forbidden=1
  fi
  if grep -Eiq 'cannot be preloaded' "$log_file"; then
    forbidden=1
  fi
  # The AppImageKit AppRun's own failure strings. These became reachable when the
  # bundler moved to linuxdeploy: AppRun is now a bash wrapper that execs
  # AppRun.wrapped, which locates the binary by parsing Exec= from the AppDir's
  # .desktop file. Both steps can fail without the app ever starting.
  if grep -Eiq \
    'AppRun\.wrapped.*(not found|No such file)|Error: No \.desktop files found|Error: Executable not found' \
    "$log_file"; then
    forbidden=1
  fi
  if grep -Eiq 'error while loading shared libraries' "$log_file"; then
    forbidden=1
  fi

  # Name this failure explicitly. It exits 101 like any other Rust panic, and the
  # generic "status 101" message sent one investigation looking at non-fatal
  # `=> not found` ldd lines instead of the actual cause.
  if grep -Eq "unsupported transport 'disabled'|single-instance/src/platform_impl/linux\.rs" \
    "$log_file"; then
    forbidden=1
    echo "[appimage-runtime] Detected the single-instance D-Bus panic — the smoke" \
      "environment has no usable session bus. Check the dbus-run-session wrapper" \
      "above and that 'dbus'/'dbus-x11' are installed on the runner." >&2
  fi

  # The desktop process is expected to remain alive until timeout ends the
  # startup window. An earlier clean exit is a failure as well as loader output.
  if [ "$forbidden" -ne 0 ] || [ "$status" -ne 124 ]; then
    echo "[appimage-runtime] AppImage startup smoke failed (status $status):" >&2
    sed 's/^/[appimage-runtime]   /' "$log_file" >&2
    return 1
  fi

  grep -Ei 'loader|loading|cef|startup|started|ready' "$log_file" \
    | sed 's/^/[appimage-runtime]   /' \
    || true
  echo "[appimage-runtime] Application remained alive for the 15-second startup window"
}

validate_final_appimage() (
  local image="$1"
  if ! image="$(realpath "$image")"; then
    runtime_validation_error "could not resolve AppImage path: $1"
    return 1
  fi
  if [ ! -f "$image" ] || [ ! -x "$image" ]; then
    runtime_validation_error "AppImage must be an executable regular file: $image"
    return 1
  fi
  command -v patchelf >/dev/null 2>&1 \
    || { runtime_validation_error "patchelf is required for final AppImage validation"; return 1; }

  local temp_root
  temp_root="$(mktemp -d)"
  trap 'rm -rf -- "$temp_root"' EXIT
  local foreign_cwd="$temp_root/foreign-cwd"
  local extraction_log="$temp_root/extraction.log"
  local smoke_log="$temp_root/smoke.log"
  mkdir -p "$foreign_cwd"

  if ! (
    cd "$foreign_cwd"
    "$image" --appimage-extract
  ) >"$extraction_log" 2>&1; then
    echo "[appimage-runtime] AppImage extraction failed:" >&2
    sed 's/^/[appimage-runtime]   /' "$extraction_log" >&2
    return 1
  fi

  local appdir="$foreign_cwd/squashfs-root"
  if [ ! -d "$appdir" ]; then
    runtime_validation_error "extraction did not create $appdir"
    return 1
  fi
  validate_extracted_appdir "$appdir" || return 1

  if [ "${APPIMAGE_RUNTIME_SMOKE:-0}" = "1" ]; then
    smoke_extracted_apprun "$appdir" "$foreign_cwd" "$smoke_log" || return 1
  else
    echo "[appimage-runtime] Static validation complete; executable smoke disabled for this architecture"
  fi
)

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
  [ "$#" -eq 1 ] || {
    echo "Usage: $0 <final.AppImage>" >&2
    exit 2
  }
  # Pin the production contract for a direct invocation so a caller-supplied
  # `APPIMAGE_EXPECTED_NEEDED` cannot disarm it on a real artifact. This reads the
  # same constant as the default in `validate_extracted_appdir`, so unlike the
  # previous hardcode there is no second copy to go stale.
  APPIMAGE_EXPECTED_NEEDED="$APPIMAGE_PRODUCTION_NEEDED" \
    validate_final_appimage "$1"
fi
