//! Aggregated integration-test target for the `tests/in_process/` suites.
//!
//! Each file under `tests/in_process/` boots the core router (or drives a
//! public API) inside the test process. They used to be ~20 separate
//! `tests/*.rs` targets, and every target statically relinks the whole
//! `openhuman` rlib, so the test build paid ~20 full-crate link steps. Folding
//! them into this one target links once. The module list is generated by
//! `build.rs` (`in_process_mods.rs`), so a new `tests/in_process/*.rs` file is
//! picked up automatically and cannot be skipped.
//!
//! Sharing a process is what makes three pieces of global state explicit:
//!
//! - **Env.** Suites that mutate process env (`HOME`, `OPENHUMAN_WORKSPACE`,
//!   backend-URL overrides, ...) hold `env_guard::env_lock()` for the whole
//!   test, so they serialize against each other while env-free tests still run
//!   in parallel.
//! - **RPC bearer.** `core::auth::RPC_TOKEN` is first-writer-wins, so suites
//!   read the live token through `rpc_auth::rpc_token()` instead of choosing
//!   their own.
//! - **Backend transport.** `tinyhumans_boot::boot()` installs the SDK-backed
//!   transport once for the process.
//!
//! Suites that need a process of their own (global `OnceCell`s, a real
//! keyring, binary spawning) stay separate `[[test]]` targets.

#![allow(dead_code)]

#[path = "support/env_guard.rs"]
pub mod env_guard;
#[path = "support/rpc_auth.rs"]
pub mod rpc_auth;
#[path = "support/rpc_harness.rs"]
pub mod rpc_harness;
#[path = "support/scripted_stack.rs"]
pub mod scripted_stack;
#[path = "support/tinyhumans_boot.rs"]
pub mod tinyhumans_boot;

include!(concat!(env!("OUT_DIR"), "/in_process_mods.rs"));
