use super::*;

pub(super) const CAPABILITIES: &[Capability] = &[
Capability {
        id: "workflows.configure",
        name: "Configure Workflows",
        domain: "workflows",
        category: CapabilityCategory::Workflows,
        description: "Open workflow setup and update workflow-specific configuration.",
        how_to: "Intelligence > Workflows > Setup or Connections",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
    Capability {
        id: "workflows.connection_status",
        name: "Monitor Workflow Connection Status",
        domain: "workflows",
        category: CapabilityCategory::Workflows,
        description: "See whether a workflow-backed integration is connected, offline, or needs setup.",
        how_to: "Intelligence > Workflows or Connections",
        status: CapabilityStatus::Beta,
        privacy: None,
    },
    Capability {
        id: "workflows.sync_manual",
        name: "Manually Sync Workflow Data",
        domain: "workflows",
        category: CapabilityCategory::Workflows,
        description: "Trigger a manual data sync for a workflow integration.",
        how_to: "Intelligence > Workflows > Workflow card > Sync",
        status: CapabilityStatus::Beta,
        privacy: DERIVED_TO_BACKEND,
    },
    Capability {
        id: "workflows.tinyfish_web_automation",
        name: "TinyFish Web Automation",
        domain: "workflows",
        category: CapabilityCategory::Workflows,
        description:
            "Search the web, render JavaScript-heavy pages, and run goal-based browser automations through TinyFish.",
        how_to: "Conversations > Ask the assistant to search, fetch, or automate a website with TinyFish",
        status: CapabilityStatus::Beta,
        privacy: DERIVED_TO_BACKEND,
    },
    Capability {
        id: "workflows.toggle_enabled",
        name: "Enable or Disable Workflows",
        domain: "workflows",
        category: CapabilityCategory::Workflows,
        description: "Turn individual workflows on or off without uninstalling them.",
        how_to: "Settings > Developer Options > Workflows",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
    Capability {
        id: "workflows.open_connections_hub",
        name: "Open Connections Hub",
        domain: "workflows",
        category: CapabilityCategory::Workflows,
        description: "Browse the dedicated connections hub for external workflow-backed integrations.",
        how_to: "Connections",
        status: CapabilityStatus::Beta,
        privacy: None,
    },
    // ── Composio direct mode (BYO API key) ──────────────────────────
    //
    // Composio shipped with two integration paths:
    //   1. Backend-proxied (default) — calls through api.tinyhumans.ai;
    //      backend owns the Composio API key, billing, allowlist, and
    //      HMAC-verified trigger fan-out via socket.io.
    //   2. Direct (BYO key) — core calls backend.composio.dev directly
    //      with the user's own key. Sovereign / offline-friendly, but
    //      tool execution only — real-time trigger webhooks are NOT
    //      routed in direct mode (they still require the backend).
    Capability {
        id: "composio.direct_mode",
        name: "Composio Direct Mode (BYO API Key)",
        domain: "workflows",
        category: CapabilityCategory::Workflows,
        description:
            "Route Composio tool calls directly to backend.composio.dev with your own API key, \
             bypassing the OpenHuman backend proxy. Tool execution only — trigger webhooks still \
             require backend mode.",
        how_to: "Settings > Skills > Composio > Direct mode",
        status: CapabilityStatus::Beta,
        privacy: COMPOSIO_DIRECT_CREDENTIALS,
    },
    Capability {
        id: "composio.direct_mode_triggers_gap",
        name: "Composio Triggers (Direct Mode — Limited)",
        domain: "workflows",
        category: CapabilityCategory::Workflows,
        description:
            "Composio real-time trigger webhooks (Gmail new-message, Slack new-message, …) \
             currently arrive over wss://api.tinyhumans.ai/socket.io and require backend mode. \
             Direct-mode users get synchronous tool execution but not async trigger push in \
             this release.",
        how_to: "Switch to Backend mode to receive triggers, or wait for the direct trigger sink follow-up",
        status: CapabilityStatus::ComingSoon,
        privacy: None,
    },
    Capability {
        id: "workflows.connect_google",
        name: "Connect Google",
        domain: "workflows",
        category: CapabilityCategory::Workflows,
        description: "Connect Google services for email, contacts, and calendar workflows.",
        how_to: "Connections > OAuth",
        status: CapabilityStatus::ComingSoon,
        privacy: LOCAL_CREDENTIALS,
    },
    Capability {
        id: "workflows.connect_notion",
        name: "Connect Notion",
        domain: "workflows",
        category: CapabilityCategory::Workflows,
        description: "Connect Notion for workspace sync and productivity workflows.",
        how_to: "Connections > OAuth",
        status: CapabilityStatus::ComingSoon,
        privacy: LOCAL_CREDENTIALS,
    },
    Capability {
        id: "workflows.connect_web3_wallet",
        name: "Connect Web3 Wallet",
        domain: "workflows",
        category: CapabilityCategory::Workflows,
        description: "Set up local EVM, BTC, Solana, and Tron wallet identities from one recovery phrase.",
        how_to: "Settings > Crypto > Recovery Phrase or Connections",
        status: CapabilityStatus::Beta,
        privacy: LOCAL_CREDENTIALS,
    },
    Capability {
        id: "workflows.wallet_execution",
        name: "Wallet Execution Tools",
        domain: "wallet",
        category: CapabilityCategory::Workflows,
        description: "Read addresses and balances, prepare/confirm/execute native + token transfers (ERC20/SPL/TRC20/BEP20), and inspect transactions (status, receipt, lookup) across the connected wallet (EVM, BTC, Solana, Tron). Quote-first; signing stays local.",
        how_to: "Use wallet.* RPC methods (balances, prepare_transfer, execute_prepared, tx_status, tx_receipt, lookup_tx) via the agent or core_rpc_relay, or via Settings > Crypto > Wallet Balances.",
        status: CapabilityStatus::Beta,
        privacy: LOCAL_CREDENTIALS,
    },
    Capability {
        id: "workflows.web3_defi",
        name: "Web3 Swaps & Bridges",
        domain: "web3",
        category: CapabilityCategory::Workflows,
        description: "Quote and execute cross-chain swaps and bridges (deBridge) plus generic EVM dapp contract calls, built on the local wallet's signing. EVM/Solana(/BTC); signing stays local.",
        how_to: "Use web3_swap.* / web3_bridge.* / web3_dapp.* RPC methods (quote/execute, web3_swap.routes) via the agent or core_rpc_relay.",
        status: CapabilityStatus::Beta,
        privacy: LOCAL_CREDENTIALS,
    },
    Capability {
        id: "workflows.x402_payments",
        name: "x402 Machine Payments",
        domain: "x402",
        category: CapabilityCategory::Workflows,
        description: "Automatic HTTP 402 payment handling for machine-payable APIs via the x402 protocol. When an API returns 402 Payment Required, the agent pays with USDC on Solana using the local wallet and retries. Budget enforcement with per-request, daily, and monthly caps.",
        how_to: "Use x402.* RPC methods (get_summary, list_payments, update_budget) to manage spending. Payments happen automatically when the http_request tool encounters a 402 with a PAYMENT-REQUIRED header.",
        status: CapabilityStatus::Beta,
        privacy: LOCAL_CREDENTIALS,
    },
    Capability {
        id: "workflows.connect_crypto_exchange",
        name: "Connect Crypto Exchange",
        domain: "workflows",
        category: CapabilityCategory::Workflows,
        description: "Connect supported exchanges for trading and portfolio workflows.",
        how_to: "Connections",
        status: CapabilityStatus::ComingSoon,
        privacy: None,
    },
    Capability {
        id: "local_ai.download_model",
        name: "Download Local Models",
        domain: "local_ai",
        category: CapabilityCategory::LocalAI,
        description: "Download and bootstrap local AI runtimes and model bundles.",
        how_to: "Settings > Local AI Model",
        status: CapabilityStatus::Beta,
        privacy: MODEL_DOWNLOAD,
    },
    Capability {
        id: "local_ai.configure_provider",
        name: "Configure Local Provider",
        domain: "local_ai",
        category: CapabilityCategory::LocalAI,
        description: "Select Ollama, LM Studio, MLX, or a generic local OpenAI-compatible server as the local model provider and configure the endpoint.",
        how_to: "Connections → API keys → LLM, or use provider strings: ollama:<model>, lmstudio:<model>, mlx:<model>, local-openai:<model>",
        status: CapabilityStatus::Beta,
        privacy: None,
    },
    Capability {
        id: "local_ai.manage_model_assets",
        name: "Manage Model Assets",
        domain: "local_ai",
        category: CapabilityCategory::LocalAI,
        description: "Inspect asset status and download specific chat, vision, embedding, STT, or TTS assets.",
        how_to: "Settings > Local AI Model > Advanced > Capability Assets",
        status: CapabilityStatus::Beta,
        privacy: None,
    },
    Capability {
        id: "local_ai.model_context_check",
        name: "Model Context Requirement Check",
        domain: "local_ai",
        category: CapabilityCategory::LocalAI,
        description: "Diagnostics report each installed Ollama model's native context window and reject any model below the minimum the memory layer requires (so short-context models can't silently truncate and corrupt recall).",
        how_to: "Settings > Local AI Model > Run Diagnostics",
        status: CapabilityStatus::Beta,
        privacy: None,
    },
    Capability {
        id: "local_ai.embed_text",
        name: "Generate Text Embeddings",
        domain: "local_ai",
        category: CapabilityCategory::LocalAI,
        description: "Create local vector embeddings for text input.",
        how_to: "Settings > Local AI Model > Advanced > Test Embeddings",
        status: CapabilityStatus::Beta,
        privacy: LOCAL_RAW,
    },
    Capability {
        id: "local_ai.text_to_speech",
        name: "Text to Speech (Local)",
        domain: "local_ai",
        category: CapabilityCategory::LocalAI,
        description:
            "Synthesize speech locally with Piper via the voice TTS factory. PIPER_BIN points \
             at the binary; the voice .onnx ships with the installer. Returns a synthetic \
             viseme timeline (full forced-alignment lives behind the cloud provider for now).",
        how_to: "Settings > Voice > TTS Provider = Piper",
        status: CapabilityStatus::Beta,
        privacy: None,
    },
    Capability {
        id: "local_ai.vision_processing",
        name: "Vision Processing",
        domain: "local_ai",
        category: CapabilityCategory::LocalAI,
        description: "Run vision prompts against images using a local multimodal model.",
        how_to: "Settings > Local AI Model > Advanced > Test Vision Prompt",
        status: CapabilityStatus::Beta,
        privacy: None,
    },
    Capability {
        id: "local_ai.direct_prompting",
        name: "Direct Model Prompting",
        domain: "local_ai",
        category: CapabilityCategory::LocalAI,
        description: "Send a direct prompt to the local model without using the cloud API.",
        how_to: "Settings > Local AI Model > Advanced > Test Custom Prompt",
        status: CapabilityStatus::Beta,
        privacy: None,
    },
    Capability {
        id: "local_ai.piper_installer",
        name: "Piper Installer (Local TTS)",
        domain: "local_ai",
        category: CapabilityCategory::LocalAI,
        description:
            "One-click download of the Piper binary archive and the bundled en_US-lessac-medium \
             voice (.onnx + .onnx.json) into the workspace so local Text-to-Speech runs without \
             manual setup. Atomic rename guarantees no half-written voice files are ever read \
             by the runtime.",
        how_to: "Settings > Voice > Voice Providers > Install Piper",
        status: CapabilityStatus::Beta,
        privacy: MODEL_DOWNLOAD,
    },
    Capability {
        id: "local_ai.python_runtime_installer",
        name: "Managed Python Runtime",
        domain: "runtime_python",
        category: CapabilityCategory::LocalAI,
        description:
            "Download and reuse an OpenHuman-managed CPython runtime for Python-backed local integrations such as MCP servers, with a system-Python override reserved for development.",
        how_to: "Configured by the core `runtime_python` module; future UI surfaces can expose install state and overrides.",
        status: CapabilityStatus::Beta,
        privacy: MODEL_DOWNLOAD,
    },
    Capability {
        id: "team.create",
        name: "Create Teams",
        domain: "team",
        category: CapabilityCategory::Team,
        description: "Create a team and start collaborating with shared billing and members.",
        how_to: "Settings > Team",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
    Capability {
        id: "team.join_via_invite_code",
        name: "Join Teams via Invite Code",
        domain: "team",
        category: CapabilityCategory::Team,
        description: "Join an existing team using an invite code.",
        how_to: "Invites > Redeem an Invite Code",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
    Capability {
        id: "team.switch_active_team",
        name: "Switch Active Team",
        domain: "team",
        category: CapabilityCategory::Team,
        description: "Switch which team is currently active in the app.",
        how_to: "Settings > Team",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
    Capability {
        id: "team.leave",
        name: "Leave Teams",
        domain: "team",
        category: CapabilityCategory::Team,
        description: "Leave a team that you no longer want to participate in.",
        how_to: "Settings > Team",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
    Capability {
        id: "team.manage_members",
        name: "Manage Team Members",
        domain: "team",
        category: CapabilityCategory::Team,
        description: "Review members and change team roles when you have permission.",
        how_to: "Settings > Team > Manage team > Members",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
    Capability {
        id: "team.generate_invite_codes",
        name: "Generate Invite Codes",
        domain: "team",
        category: CapabilityCategory::Team,
        description: "Create invite codes to bring new members into a team.",
        how_to: "Settings > Team > Manage team > Invites",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
    Capability {
        id: "team.track_invite_usage",
        name: "Track Invite Usage",
        domain: "team",
        category: CapabilityCategory::Team,
        description: "View invite usage counts, limits, and revoke team invites.",
        how_to: "Settings > Team > Manage team > Invites",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
    Capability {
        id: "auth.login_oauth",
        name: "Login via OAuth",
        domain: "auth",
        category: CapabilityCategory::Auth,
        description: "Sign in with the app's supported provider-based authentication flow.",
        how_to: "Welcome",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
    Capability {
        id: "auth.onboarding_setup",
        name: "Onboarding Setup",
        domain: "auth",
        category: CapabilityCategory::Auth,
        description: "Walk through onboarding to configure initial permissions and preferences.",
        how_to: "Onboarding",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
    Capability {
        id: "auth.configure_tool_access",
        name: "Configure Tool Access",
        domain: "auth",
        category: CapabilityCategory::Auth,
        description: "Choose which built-in tools OpenHuman can use on your behalf during setup.",
        how_to: "Onboarding > Enable Tools",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
    Capability {
        id: "auth.backup_recovery_phrase",
        name: "Back Up Recovery Phrase",
        domain: "auth",
        category: CapabilityCategory::Auth,
        description: "Generate and save a recovery phrase used to secure and restore encrypted app data.",
        how_to: "Onboarding > Recovery Phrase",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
    Capability {
        id: "auth.import_recovery_phrase",
        name: "Import Recovery Phrase",
        domain: "auth",
        category: CapabilityCategory::Auth,
        description: "Import an existing recovery phrase to restore encrypted app data.",
        how_to: "Onboarding > Recovery Phrase > I already have a recovery phrase",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
    Capability {
        id: "auth.logout",
        name: "Logout",
        domain: "auth",
        category: CapabilityCategory::Auth,
        description: "Sign out of the current session.",
        how_to: "Settings > Log out",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
    Capability {
        id: "channels.connect_platform",
        name: "Connect Messaging Platforms",
        domain: "channels",
        category: CapabilityCategory::Channels,
        description: "Connect supported messaging platforms such as Telegram or Discord.",
        how_to: "Connections > Channels",
        status: CapabilityStatus::Beta,
        privacy: None,
    },
    Capability {
        id: "channels.telegram_remote_control",
        name: "Telegram Remote Control",
        domain: "channels",
        category: CapabilityCategory::Channels,
        description:
            "Operate OpenHuman from Telegram with slash commands: /status, /sessions, /new, and /help.",
        how_to: "Connections > Channels > Telegram (connect), then message the bot",
        status: CapabilityStatus::Beta,
        privacy: None,
    },
    Capability {
        id: "channels.disconnect_platform",
        name: "Disconnect Messaging Platforms",
        domain: "channels",
        category: CapabilityCategory::Channels,
        description: "Disconnect a previously configured messaging platform.",
        how_to: "Connections > Channels",
        status: CapabilityStatus::Beta,
        privacy: None,
    },
    Capability {
        id: "channels.test_credentials",
        name: "Test Channel Credentials",
        domain: "channels",
        category: CapabilityCategory::Channels,
        description: "Validate platform credentials or connection state before using a channel.",
        how_to: "Connections > Channels",
        status: CapabilityStatus::Beta,
        privacy: None,
    },
    Capability {
        id: "channels.set_default_channel",
        name: "Set Default Messaging Channel",
        domain: "channels",
        category: CapabilityCategory::Channels,
        description: "Choose which messaging channel should be used by default.",
        how_to: "Connections > Channels",
        status: CapabilityStatus::Beta,
        privacy: None,
    },
    Capability {
        id: "channels.whatsapp_read_messages",
        name: "Read WhatsApp Messages",
        domain: "channels",
        category: CapabilityCategory::Channels,
        description: "Read and search WhatsApp Web conversations and messages after connecting WhatsApp in OpenHuman. Data is stored locally only and never transmitted.",
        how_to: "Connect WhatsApp Web via Channels, then ask the agent to read or summarise your messages.",
        status: CapabilityStatus::Beta,
        privacy: LOCAL_RAW,
    },
    Capability {
        id: "channels.mcp_registry_browse",
        name: "Browse MCP Server Registry",
        domain: "channels",
        category: CapabilityCategory::Channels,
        description: "Search and discover MCP servers from the Smithery.ai and official modelcontextprotocol registries.",
        how_to: "Skills > MCP > Browse catalog",
        status: CapabilityStatus::Beta,
        privacy: Some(CapabilityPrivacy {
            leaves_device: true,
            data_kind: PrivacyDataKind::Metadata,
            destinations: &["Smithery.ai registry API", "modelcontextprotocol registry API"],
        }),
    },
    Capability {
        id: "channels.mcp_server_install",
        name: "Install MCP Servers",
        domain: "channels",
        category: CapabilityCategory::Channels,
        description: "Install MCP servers locally — both local stdio subprocesses and hosted HTTP-remote servers. Required env vars are stored encrypted and never included in logs or responses. Can also be done conversationally via the MCP setup assistant.",
        how_to: "Skills > MCP > Browse catalog > Install, or ask the assistant to \"set up the <name> MCP server\"",
        status: CapabilityStatus::Beta,
        privacy: LOCAL_CREDENTIALS,
    },
    Capability {
        id: "channels.mcp_server_connect",
        name: "Connect / Reconfigure MCP Servers",
        domain: "channels",
        category: CapabilityCategory::Channels,
        description: "Spawn and manage MCP server connections (stdio subprocess or HTTP-remote). Reconfigure stored env vars and reconnect without uninstalling.",
        how_to: "Skills > MCP > select a server > Connect / Reconfigure",
        status: CapabilityStatus::Beta,
        privacy: Some(CapabilityPrivacy {
            leaves_device: true,
            data_kind: PrivacyDataKind::Derived,
            destinations: &["Configured MCP endpoint(s)"],
        }),
    },
    Capability {
        id: "channels.mcp_connection_alerts",
        name: "MCP Connection Health Alerts",
        domain: "channels",
        category: CapabilityCategory::Channels,
        description: "Watch installed MCP servers in the background. Each non-nominal liveness-probe outcome (a slow answer, a dropped transport, a reconnect that succeeded or failed) is recorded in the developer Event Log — an answered probe is not, so a healthy server stays silent — and a server that stays down, comes back after failing, or cannot start because its launcher runtime is missing raises a notification.",
        how_to: "Automatic. Settings > Developer > Event Log (filter: mcp) for the stream; Notifications for the alerts",
        status: CapabilityStatus::Beta,
        privacy: None,
    },
    Capability {
        id: "channels.mcp_tool_call",
        name: "Invoke MCP Server Tools",
        domain: "channels",
        category: CapabilityCategory::Channels,
        description: "Call tools exposed by connected MCP servers. Tools are surfaced to the agent and runnable from the tool playground.",
        how_to: "Skills > MCP > select a connected server > Tools > Try, or ask the assistant in Chat",
        status: CapabilityStatus::Beta,
        privacy: Some(CapabilityPrivacy {
            leaves_device: true,
            data_kind: PrivacyDataKind::Derived,
            destinations: &["Configured MCP endpoint(s)"],
        }),
    },
    Capability {
        id: "settings.configure_ai",
        name: "Configure AI",
        domain: "settings",
        category: CapabilityCategory::Settings,
        description: "Configure managed, local, custom, and built-in BYOK LLM providers, including SumoPod and other OpenAI-compatible gateways, plus per-workload routing preferences.",
        how_to: "Connections → API keys → LLM",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
    Capability {
        id: "settings.core_connection",
        name: "Run the Core Somewhere Else",
        domain: "settings",
        category: CapabilityCategory::Settings,
        description: "Choose where the OpenHuman core runs: inside this app, at a URL \
            you point it at, in a Docker container, on another machine over SSH, or in a \
            container on another machine. OpenHuman starts the core, connects to it, and \
            shuts it down when you switch away. Where it runs and what contains it are \
            separate choices, so SSH and Docker combine without being a third option.",
        how_to: "Settings > Core connection",
        status: CapabilityStatus::Beta,
        privacy: Some(CapabilityPrivacy {
            leaves_device: true,
            data_kind: PrivacyDataKind::Raw,
            // `Raw`, because everything the core holds - the conversations
            // themselves, memory, stored credentials - lives wherever the core
            // runs. Choosing a machine over SSH is choosing to put all of it
            // there. That is the disclosure that matters here and the one a
            // hostname field makes easy to overlook, so it is stated at the
            // strongest kind rather than softened to `Derived`.
            destinations: &["The machine you configure, when the core runs off this device"],
        }),
    },
    Capability {
        id: "settings.persona_pack",
        name: "Persona Pack",
        domain: "settings",
        category: CapabilityCategory::Settings,
        description: "Personalize the assistant across one or more agent profiles: set a display name and description, edit or reset each profile's SOUL.md identity (kept in its own home under personalities/<id>/ and re-read every message), give a profile its own dedicated memory subtree or its own working directory, drop private skills under personalities/<id>/skills/ that only that profile can discover, attribute a scheduled cron job to a profile so it runs with that profile's identity, memory, and permissions, and reach mascot avatar and voice settings. Multiple profiles can run with isolated identity, memory, skills, and workspace state.",
        how_to: "Settings > Persona",
        status: CapabilityStatus::Beta,
        privacy: GITHUB_MASCOT_MANIFEST,
    },
    Capability {
        id: "settings.manage_privacy_analytics",
        name: "Manage Privacy and Analytics",
        domain: "settings",
        category: CapabilityCategory::Settings,
        description: "Control privacy, analytics, and related data handling preferences. \
            When enabled, anonymous crash reports are sent to Sentry and anonymous usage \
            analytics (page views, feature engagement) are sent to Google Analytics. \
            No personal data, messages, or credentials are ever included.",
        how_to: "Settings > Privacy (direct route)",
        status: CapabilityStatus::Stable,
        privacy: DIAGNOSTICS_TO_BACKEND,
    },
    Capability {
        id: "settings.view_billing",
        name: "View Billing",
        domain: "settings",
        category: CapabilityCategory::Settings,
        description: "Open subscription, included usage, and pay-as-you-go billing views for your active team.",
        how_to: "Settings > Billing & Usage",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
    Capability {
        id: "settings.manage_subscription_plan",
        name: "Manage Subscription Plan",
        domain: "settings",
        category: CapabilityCategory::Settings,
        description: "Upgrade plans or open the billing portal to manage subscription-backed usage tiers.",
        how_to: "Settings > Billing & Usage",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
    Capability {
        id: "settings.manage_credits",
        name: "Manage Credits",
        domain: "settings",
        category: CapabilityCategory::Settings,
        description: "View pay-as-you-go credit balances, top up overage credits, and configure auto-recharge.",
        how_to: "Settings > Billing & Usage",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
    Capability {
        id: "settings.add_payment_methods",
        name: "Add Payment Methods",
        domain: "settings",
        category: CapabilityCategory::Settings,
        description: "Add or manage saved payment methods for billing and auto-recharge.",
        how_to: "Settings > Billing & Usage > Payment Methods",
        status: CapabilityStatus::Stable,
        privacy: None,
    },
];
