//! RPC handlers for chat_with_data domain.
use super::{engine, sql_gen, types::*};
use serde_json::{json, Map, Value};
use tracing::debug;

pub async fn handle_register_dataset(p: Map<String, Value>) -> Result<Value, String> {
    let name = p.get("name").and_then(|v| v.as_str()).unwrap_or("");
    if name.is_empty() {
        return Ok(json!({"ok": false, "error": "name is required"}));
    }
    let source = match p.get("source").and_then(|v| v.as_str()).unwrap_or("csv") {
        "json" => DataSource::Json,
        "sqlite" => DataSource::Sqlite,
        "api" => DataSource::Api,
        _ => DataSource::Csv,
    };
    let columns: Vec<String> = p
        .get("columns")
        .and_then(|v| v.as_array())
        .map(|a| {
            a.iter()
                .filter_map(|v| v.as_str().map(String::from))
                .collect()
        })
        .unwrap_or_default();
    let row_count = p.get("row_count").and_then(|v| v.as_u64()).unwrap_or(0);
    debug!(name = %name, source = ?source, "[chat_with_data] register_dataset RPC");
    match engine::register_dataset(name, source, columns, row_count) {
        Ok(d) => Ok(
            json!({"ok":true,"dataset_id":d.id,"name":d.name,"columns":d.columns,"row_count":d.row_count}),
        ),
        Err(e) => Ok(json!({"ok": false, "error": e})),
    }
}

pub async fn handle_query(p: Map<String, Value>) -> Result<Value, String> {
    let id = p.get("dataset_id").and_then(|v| v.as_str()).unwrap_or("");
    let question = p.get("question").and_then(|v| v.as_str()).unwrap_or("");

    if id.is_empty() {
        return Ok(json!({"ok": false, "error": "dataset_id is required"}));
    }
    if question.is_empty() {
        return Ok(json!({"ok": false, "error": "question is required"}));
    }
    if question.len() > 2000 {
        return Ok(json!({"ok": false, "error": "question exceeds 2000 chars"}));
    }

    debug!(dataset_id = %id, question_len = question.len(), "[chat_with_data] query RPC");

    // Get dataset schema for context.
    let ds = match engine::get_dataset(id) {
        Ok(d) => d,
        Err(e) => return Ok(json!({"ok": false, "error": e})),
    };

    // Try LLM-powered SQL generation for complex queries.
    let pattern_result = sql_gen::generate_sql_for_question(&ds.id, &ds.columns, question);

    if pattern_result.method == sql_gen::SqlGenMethod::Fallback {
        // Pattern matching couldn't handle it — try LLM.
        if let Some(llm_sql) = try_llm_sql_gen(&ds, question).await {
            // Validate LLM-generated SQL.
            if sql_gen::validate_sql(&llm_sql).is_ok() {
                if sql_gen::is_safe_query(&llm_sql).is_ok() {
                    let answer = format!(
                        "Generated SQL (LLM): `{}` — targeting '{}' ({} rows)",
                        llm_sql, ds.name, ds.row_count
                    );
                    return Ok(json!({
                        "ok": true, "answer": answer, "confidence": 0.85,
                        "sources": 1, "caveats": ["Generated by LLM, validated by sqlparser"],
                        "source": "llm"
                    }));
                }
            }
        }
    }

    // Use pattern-based result (or fallback).
    match engine::query_dataset(id, question) {
        Ok(r) => Ok(
            json!({"ok":true,"answer":r.answer,"confidence":r.confidence,"sources":r.sources.len(),"caveats":r.caveats,"source":"pattern"}),
        ),
        Err(e) => Ok(json!({"ok":false,"error":e})),
    }
}

/// Attempt LLM-powered SQL generation for complex queries.
async fn try_llm_sql_gen(ds: &DatasetMeta, question: &str) -> Option<String> {
    use crate::openhuman::config::ops::load_config_with_timeout;
    use crate::openhuman::inference::provider::create_chat_provider;

    let config = load_config_with_timeout().await.ok()?;
    let (provider, model) = create_chat_provider("agentic", &config).ok()?;

    let prompt = format!(
        "Generate a single SQL SELECT query for this question. Return ONLY the SQL, no explanation.\n\nTable: {}\nColumns: {}\nRow count: {}\n\nQuestion: {}\n\nSQL:",
        ds.id,
        ds.columns.join(", "),
        ds.row_count,
        question
    );

    let system = "You are a SQL expert. Generate only valid SELECT queries. Never use DROP, DELETE, UPDATE, INSERT, ALTER, or TRUNCATE.";

    let text = provider
        .chat_with_system(Some(system), &prompt, &model, 0.1)
        .await
        .ok()?;

    // Strip markdown code fences if present.
    let trimmed = text.trim();
    let sql = trimmed
        .strip_prefix("```sql")
        .or_else(|| trimmed.strip_prefix("```"))
        .unwrap_or(trimmed)
        .strip_suffix("```")
        .unwrap_or(trimmed)
        .trim()
        .to_string();

    debug!(sql_len = sql.len(), "[chat_with_data] LLM SQL generated");
    Some(sql)
}

pub async fn handle_generate_insight(p: Map<String, Value>) -> Result<Value, String> {
    let id = p.get("dataset_id").and_then(|v| v.as_str()).unwrap_or("");
    if id.is_empty() {
        return Ok(json!({"ok": false, "error": "dataset_id is required"}));
    }
    debug!(dataset_id = %id, "[chat_with_data] generate_insight RPC");
    match engine::generate_insight(id) {
        Ok(i) => {
            // Enhance insight with LLM-generated explanation.
            let explanation = try_llm_explain_insight(&i).await;
            Ok(json!({
                "ok": true, "insight_id": i.id, "type": i.insight_type,
                "title": i.title, "severity": i.severity,
                "description": i.description,
                "explanation": explanation.unwrap_or_else(|| i.description.clone()),
            }))
        }
        Err(e) => Ok(json!({"ok":false,"error":e})),
    }
}

/// LLM-powered natural language explanation of detected anomalies.
async fn try_llm_explain_insight(insight: &Insight) -> Option<String> {
    use crate::openhuman::config::ops::load_config_with_timeout;
    use crate::openhuman::inference::provider::create_chat_provider;

    let config = load_config_with_timeout().await.ok()?;
    let (provider, model) = create_chat_provider("agentic", &config).ok()?;

    let prompt = format!(
        "Explain this data anomaly in plain language. What might have caused it and what should the user do?\n\nDataset: {}\nType: {:?}\nTitle: {}\nDetails: {}\n\nProvide a 2-3 sentence explanation:",
        insight.dataset, insight.insight_type, insight.title, insight.description
    );

    let system = "You are a data analyst assistant. Explain anomalies clearly and suggest actionable next steps. Be concise.";

    let text = provider
        .chat_with_system(Some(system), &prompt, &model, 0.5)
        .await
        .ok()?;

    debug!(insight_id = %insight.id, "[chat_with_data] LLM explanation generated");
    Some(text.trim().to_string())
}

pub async fn handle_list_datasets(_p: Map<String, Value>) -> Result<Value, String> {
    let all: Vec<Value> = engine::list_datasets()
        .iter()
        .map(|d| json!({"id":d.id,"name":d.name,"source":d.source,"row_count":d.row_count}))
        .collect();
    Ok(json!({"ok":true,"datasets":all}))
}

pub async fn handle_list_insights(_p: Map<String, Value>) -> Result<Value, String> {
    let all: Vec<Value> = engine::list_insights()
        .iter()
        .map(|i| json!({"id":i.id,"type":i.insight_type,"title":i.title,"severity":i.severity}))
        .collect();
    Ok(json!({"ok":true,"insights":all}))
}

pub async fn handle_get_dataset(p: Map<String, Value>) -> Result<Value, String> {
    let id = p.get("dataset_id").and_then(|v| v.as_str()).unwrap_or("");
    match engine::get_dataset(id) {
        Ok(d) => Ok(
            json!({"ok":true,"dataset_id":d.id,"name":d.name,"source":d.source,"columns":d.columns,"row_count":d.row_count}),
        ),
        Err(e) => Ok(json!({"ok":false,"error":e})),
    }
}

pub async fn handle_ingest_rows(p: Map<String, Value>) -> Result<Value, String> {
    let id = p.get("dataset_id").and_then(|v| v.as_str()).unwrap_or("");
    if id.is_empty() {
        return Ok(json!({"ok": false, "error": "dataset_id is required"}));
    }
    let rows_val = p.get("rows").and_then(|v| v.as_array());
    let rows: Vec<std::collections::HashMap<String, f64>> = rows_val
        .map(|arr| {
            arr.iter()
                .filter_map(|row| {
                    row.as_object().map(|obj| {
                        obj.iter()
                            .filter_map(|(k, v)| v.as_f64().map(|f| (k.clone(), f)))
                            .collect()
                    })
                })
                .collect()
        })
        .unwrap_or_default();
    let count = rows.len();
    engine::ingest_rows(id, rows);
    Ok(json!({"ok": true, "ingested": count}))
}

pub async fn handle_scan_anomalies(_p: Map<String, Value>) -> Result<Value, String> {
    let insights = engine::scan_all_datasets_for_anomalies();
    let items: Vec<Value> = insights
        .iter()
        .map(
            |i| json!({"id": i.id, "title": i.title, "dataset": i.dataset, "severity": i.severity}),
        )
        .collect();
    Ok(json!({"ok": true, "insights_found": items.len(), "insights": items}))
}

pub async fn handle_delete_dataset(p: Map<String, Value>) -> Result<Value, String> {
    let id = p.get("dataset_id").and_then(|v| v.as_str()).unwrap_or("");
    if id.is_empty() {
        return Ok(json!({"ok": false, "error": "dataset_id is required"}));
    }
    match engine::delete_dataset(id) {
        Ok(()) => Ok(json!({"ok": true, "deleted": id})),
        Err(e) => Ok(json!({"ok": false, "error": e})),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[tokio::test]
    async fn query_rpc() {
        let mut p = Map::new();
        p.insert("dataset_id".into(), Value::String("sample_metrics".into()));
        p.insert("question".into(), Value::String("average value".into()));
        let r = handle_query(p).await.unwrap();
        assert_eq!(r["ok"], true);
        assert!(r["answer"].as_str().unwrap().contains("AVG"));
    }
    #[tokio::test]
    async fn list_datasets_rpc() {
        let r = handle_list_datasets(Map::new()).await.unwrap();
        assert_eq!(r["ok"], true);
    }
}
