//! Contract for the hosted `image_generation` tool.
//!
//! The tool is a hosted/provider capability, not a local Rust image renderer.
//! Runtimes that support it should persist generated bytes under a
//! session-scoped generated-media root, then return stable file paths in tool
//! output so final answers can reference concrete artifacts.

use serde::{Deserialize, Serialize};
use serde_json::json;

use super::{ImagePermission, ImageToolSpec};

/// Stable model-facing tool name.
pub const IMAGE_GENERATION_TOOL_NAME: &str = "image_generation";

/// Generated image file format requested from the hosted provider.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ImageGenerationOutputFormat {
    Png,
    Webp,
    Jpeg,
}

impl ImageGenerationOutputFormat {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Png => "png",
            Self::Webp => "webp",
            Self::Jpeg => "jpeg",
        }
    }
}

/// Build the hosted `image_generation` model-facing contract.
pub fn image_generation_spec(output_format: ImageGenerationOutputFormat) -> ImageToolSpec {
    ImageToolSpec {
        name: IMAGE_GENERATION_TOOL_NAME.to_string(),
        description: "Generate or edit raster images from a prompt and store each result as a local artifact path for the user.".to_string(),
        parameters: json!({
            "type": "object",
            "properties": {
                "prompt": {
                    "type": "string",
                    "description": "Detailed visual prompt or edit instruction for the hosted image model."
                },
                "output_path": {
                    "type": "string",
                    "description": "Optional workspace-relative or approved absolute output path. When omitted, the runtime chooses a generated-media path."
                },
                "size": {
                    "type": "string",
                    "description": "Optional output size such as 1024x1024, 1536x1024, or provider default."
                },
                "input_image_path": {
                    "type": "string",
                    "description": "Optional local image path to edit. The runtime must validate local-file access before attaching it."
                },
                "output_format": {
                    "type": "string",
                    "enum": ["png", "webp", "jpeg"],
                    "default": output_format.as_str(),
                    "description": "Requested persisted file format."
                }
            },
            "required": ["prompt"]
        }),
        permission: ImagePermission::Write,
        model_visible_image_output: false,
        writes_files: true,
    }
}

#[cfg(test)]
#[path = "image_generation_tests.rs"]
mod tests;
