use super::*;

// The adapter no longer imports these itself — the encoding lives in the crate
// now — but the tests still build fixture data by hand.
use base64::Engine as _;

// ── File-attachment marker tests ──────────────────────────────────────

/// Minimal valid PDF that `pdf-extract` will round-trip. Generated by
/// hand from the smallest known-good PDF skeleton; covers the
/// `/Pages` → `/Page` → `/Contents` → `Tj` text-object path that
/// `pdf-extract` walks to surface visible text.
const SAMPLE_PDF_BYTES: &[u8] = b"%PDF-1.4\n\
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n\
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n\
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]/Contents 4 0 R/Resources<</Font<</F1 5 0 R>>>>>>endobj\n\
4 0 obj<</Length 44>>stream\n\
BT /F1 12 Tf 72 720 Td (Hello PDF World) Tj ET\n\
endstream endobj\n\
5 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj\n\
xref\n0 6\n0000000000 65535 f\n\
trailer<</Size 6/Root 1 0 R>>\n\
startxref\n0\n%%EOF\n";

const TINY_PNG_DATA_URI: &str = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==";

#[path = "multimodal_tests_part_01_tests.rs"]
mod part_01_tests;
#[path = "multimodal_tests_part_02_tests.rs"]
mod part_02_tests;
