/**
 * Prediction Calibration Ledger — pure scoring engine.
 *
 * The user logs predictions with a subjective confidence ("80% sure the deploy
 * ships Friday"), later resolves each TRUE/FALSE, and this engine scores their
 * *calibration*: the Brier score, a 10-bin calibration curve (predicted
 * confidence vs actual hit-rate), the Murphy decomposition
 * (reliability / resolution / uncertainty), over/under-confidence, and a
 * cumulative-Brier trend. No personal-AI product scores the user's OWN
 * forecasting accuracy — forecasting platforms score communities, not your
 * private predictions woven into your assistant.
 *
 * Everything here is pure and deterministic: no React, no RPC, no
 * `Date.now()` / `Math.random()`. The Brier/decomposition math depends ONLY on
 * (confidence, outcome) pairs — never on a clock — so the same records always
 * yield the same report and every branch is unit-testable. The id/createdAt/
 * resolvedAt values are generated by the caller (container event handlers) and
 * threaded in, never minted here.
 */

export type PredictionOutcome = 'true' | 'false';

/** A single forecast the user logged. `confidence` is a 0..1 fraction. */
export interface PredictionRecord {
  id: string;
  statement: string;
  confidence: number;
  createdAt: number; // epoch seconds
  resolveBy: number | null; // optional target epoch seconds
  outcome: PredictionOutcome | null; // null while open
  resolvedAt: number | null; // epoch seconds when resolved
  category: string | null;
  notes: string | null;
}

export interface CalibrationBin {
  index: number; // 0..9
  lower: number;
  upper: number;
  midpoint: number;
  count: number; // resolved predictions whose confidence falls in this bin
  meanPredicted: number; // mean confidence of members (0 when empty)
  hitRate: number; // fraction resolved TRUE (0 when empty)
}

export interface CalibrationTrendPoint {
  through: number; // epoch seconds of the resolution at this point
  count: number; // cumulative resolved count
  brierScore: number; // cumulative Brier up to and including this point
}

export interface CalibrationReport {
  resolvedCount: number;
  openCount: number;
  brierScore: number; // mean (p - outcome)^2; 0 when none resolved
  bins: CalibrationBin[]; // always 10
  reliability: number; // calibration error (lower better)
  resolution: number; // discrimination (higher better)
  uncertainty: number; // base * (1 - base)
  overconfidence: number; // meanConfidence - baseRate (>0 overconfident)
  baseRate: number; // fraction TRUE among resolved
  meanConfidence: number; // mean predicted among resolved
  trend: CalibrationTrendPoint[];
}

export const BIN_COUNT = 10;

function clamp01(p: number): number {
  if (!Number.isFinite(p)) return 0;
  if (p < 0) return 0;
  if (p > 1) return 1;
  return p;
}

/** Clamp a confidence into [0, 1]; NaN/non-finite -> 0. */
export function normalizeConfidence(p: number): number {
  return clamp01(p);
}

export function outcomeToNumber(outcome: PredictionOutcome): 0 | 1 {
  return outcome === 'true' ? 1 : 0;
}

/** Outcome value of a record (1 for true, 0 for false/open) — no unsafe cast. */
function recordOutcomeValue(record: PredictionRecord): 0 | 1 {
  return record.outcome === 'true' ? 1 : 0;
}

export function isResolved(record: PredictionRecord): boolean {
  return record.outcome !== null;
}

export function resolvedRecords(records: PredictionRecord[]): PredictionRecord[] {
  return records.filter(isResolved);
}

/** Bin index 0..9 for a probability; p === 1 lands in bin 9 (not an 11th bin). */
export function binIndex(p: number): number {
  return Math.min(BIN_COUNT - 1, Math.max(0, Math.floor(clamp01(p) * BIN_COUNT)));
}

/** Mean of (confidence - outcome)^2 over resolved records; 0 when none. */
export function brierScore(resolved: PredictionRecord[]): number {
  if (resolved.length === 0) return 0;
  let sum = 0;
  for (const r of resolved) {
    const p = clamp01(r.confidence);
    const o = recordOutcomeValue(r);
    sum += (p - o) * (p - o);
  }
  return sum / resolved.length;
}

/** Overall fraction TRUE among resolved records; 0 when none. */
export function baseRate(resolved: PredictionRecord[]): number {
  if (resolved.length === 0) return 0;
  let trues = 0;
  for (const r of resolved) trues += recordOutcomeValue(r);
  return trues / resolved.length;
}

/** Mean predicted confidence among resolved records; 0 when none. */
export function meanConfidence(resolved: PredictionRecord[]): number {
  if (resolved.length === 0) return 0;
  let sum = 0;
  for (const r of resolved) sum += clamp01(r.confidence);
  return sum / resolved.length;
}

/** Always returns 10 bins; empty bins carry count/meanPredicted/hitRate of 0. */
export function buildBins(resolved: PredictionRecord[]): CalibrationBin[] {
  const buckets: PredictionRecord[][] = Array.from({ length: BIN_COUNT }, () => []);
  for (const r of resolved) buckets[binIndex(r.confidence)].push(r);
  return buckets.map((members, index) => {
    const lower = index / BIN_COUNT;
    const upper = (index + 1) / BIN_COUNT;
    const count = members.length;
    const meanPredicted =
      count === 0 ? 0 : members.reduce((s, r) => s + clamp01(r.confidence), 0) / count;
    const trues = members.reduce((s, r) => s + recordOutcomeValue(r), 0);
    const hitRate = count === 0 ? 0 : trues / count;
    return { index, lower, upper, midpoint: (lower + upper) / 2, count, meanPredicted, hitRate };
  });
}

/**
 * Murphy (calibration-refinement) decomposition. Reliability uses each bin's
 * MEAN predicted confidence (not the bin midpoint) so the exact identity
 * `brierScore == reliability - resolution + uncertainty` holds when forecasts
 * within a bin are equal (and is a close approximation otherwise). All terms
 * are 0 when there are no resolved records.
 */
export function murphyDecomposition(resolved: PredictionRecord[]): {
  reliability: number;
  resolution: number;
  uncertainty: number;
} {
  const n = resolved.length;
  if (n === 0) return { reliability: 0, resolution: 0, uncertainty: 0 };
  const base = baseRate(resolved);
  const bins = buildBins(resolved);
  let reliability = 0;
  let resolution = 0;
  for (const bin of bins) {
    if (bin.count === 0) continue;
    reliability += bin.count * (bin.meanPredicted - bin.hitRate) ** 2;
    resolution += bin.count * (bin.hitRate - base) ** 2;
  }
  return {
    reliability: reliability / n,
    resolution: resolution / n,
    uncertainty: base * (1 - base),
  };
}

/**
 * Cumulative Brier after each resolution, ordered by resolvedAt ascending
 * (tie-break by id) so the UI can plot whether calibration is improving.
 * Deterministic; no clock.
 */
export function buildTrend(resolved: PredictionRecord[]): CalibrationTrendPoint[] {
  const ordered = [...resolved].sort((a, b) => {
    const ta = a.resolvedAt ?? a.createdAt ?? 0;
    const tb = b.resolvedAt ?? b.createdAt ?? 0;
    if (ta !== tb) return ta - tb;
    return a.id < b.id ? -1 : a.id > b.id ? 1 : 0;
  });
  const points: CalibrationTrendPoint[] = [];
  let sumSquaredError = 0;
  ordered.forEach((r, i) => {
    const p = clamp01(r.confidence);
    const o = recordOutcomeValue(r);
    sumSquaredError += (p - o) * (p - o);
    points.push({
      through: r.resolvedAt ?? r.createdAt ?? 0,
      count: i + 1,
      brierScore: sumSquaredError / (i + 1),
    });
  });
  return points;
}

/** Compose the full calibration report. Pure function of `records`. */
export function buildCalibrationReport(records: PredictionRecord[]): CalibrationReport {
  const resolved = resolvedRecords(records);
  const { reliability, resolution, uncertainty } = murphyDecomposition(resolved);
  const base = baseRate(resolved);
  const meanConf = meanConfidence(resolved);
  return {
    resolvedCount: resolved.length,
    openCount: records.length - resolved.length,
    brierScore: brierScore(resolved),
    bins: buildBins(resolved),
    reliability,
    resolution,
    uncertainty,
    overconfidence: meanConf - base,
    baseRate: base,
    meanConfidence: meanConf,
    trend: buildTrend(resolved),
  };
}

/** True when an open prediction is past its target resolution time. */
export function isOverdue(record: PredictionRecord, nowSeconds: number): boolean {
  return record.outcome === null && record.resolveBy !== null && record.resolveBy < nowSeconds;
}

// --- Pure record transforms (id / timestamps injected by the caller) ---------

export function addRecord(
  records: PredictionRecord[],
  record: PredictionRecord
): PredictionRecord[] {
  return [...records, record];
}

/** Set outcome + resolvedAt on a matching open record; no-op if already resolved. */
export function resolveRecord(
  records: PredictionRecord[],
  id: string,
  outcome: PredictionOutcome,
  resolvedAt: number
): PredictionRecord[] {
  return records.map(r => (r.id === id && r.outcome === null ? { ...r, outcome, resolvedAt } : r));
}

export function deleteRecord(records: PredictionRecord[], id: string): PredictionRecord[] {
  return records.filter(r => r.id !== id);
}

// --- Robust parsing of the persisted (untrusted) JSON blob -------------------

function asString(v: unknown): string | null {
  return typeof v === 'string' ? v : null;
}

function asFiniteNumber(v: unknown): number | null {
  return typeof v === 'number' && Number.isFinite(v) ? v : null;
}

/**
 * Parse the loaded JSON into valid PredictionRecords, dropping anything
 * malformed. Tolerant by design: the on-disk blob is user/agent-writable and
 * a single bad entry must not break the whole ledger.
 */
export function parsePredictionRecords(raw: unknown): PredictionRecord[] {
  if (!Array.isArray(raw)) return [];
  const out: PredictionRecord[] = [];
  for (const entry of raw) {
    if (!entry || typeof entry !== 'object') continue;
    const e = entry as Record<string, unknown>;
    const id = asString(e.id);
    const statement = asString(e.statement);
    const confidence = asFiniteNumber(e.confidence);
    const createdAt = asFiniteNumber(e.createdAt);
    if (id === null || statement === null || confidence === null || createdAt === null) continue;
    const outcome = e.outcome === 'true' || e.outcome === 'false' ? e.outcome : null;
    out.push({
      id,
      statement,
      confidence: clamp01(confidence),
      createdAt,
      resolveBy: asFiniteNumber(e.resolveBy),
      outcome,
      resolvedAt: asFiniteNumber(e.resolvedAt),
      category: asString(e.category),
      notes: asString(e.notes),
    });
  }
  return out;
}
